name:                advent-of-code
version:             0.1.0.0
github:              jankramer/advent-of-code
license:             BSD3
author:              Jan Kramer
maintainer:          jan@jankramer.eu
copyright:           2017 Jan Kramer
synopsis:            Solutions to Advent of Code puzzles
description:         Please see the README on Github at <https://github.com/jankramer/advent-of-code#readme>

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - containers
    - split
    - array

executables:
  aoc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code
    - containers
    - array

tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code
